### ISSUE TITLE
Declarative API Reasoning (Breaking Changes)

### ISSUE THREAD

**Issue by jeroen-meijer** [VeryGoodOpenSource/very_good_infinite_list#14]
# Declarative API Reasoning

Hi all 👋🏻 

This is a notice to inform everybody that a breaking change might be coming to this package in the near-future. The new API can be found and tested in [the `refactor/declarative-api` branch](https://github.com/VeryGoodOpenSource/very_good_infinite_list/tree/refactor/declarative-api).

The reason for these changes originate from testing done with the package internally. We've determined that the current API, though great for some usages, is not flexible enough for our use cases. In particular, due to the package maintaining its own state, it prohibits easy usage of the declarative nature of the Flutter framework and packages that do the same, such as the [bloc library](https://bloclibrary.dev/#/).

Once further testing is finished, the outstanding branch will be merged in and the version bumped.

The new API, in its current state, can be outlined like this:
```dart
class InfiniteList<T> extends StatefulWidget {
  final ScrollController scrollController;
  final double scrollExtentThreshold;
  final Duration debounceDuration;
  final bool reverse;
  final List<T> items;
  final bool isLoading;
  final bool hasError;
  final bool hasReachedMax;
  final VoidCallback onFetchData;
  final EdgeInsets padding;
  final WidgetBuilder emptyBuilder;
  final WidgetBuilder loadingBuilder;
  final WidgetBuilder errorBuilder;
  final WidgetBuilder separatorBuilder;
  final Widget Function(BuildContext context, T item) itemBuilder;
}
```

If you have any comments or suggestions, please let us know below. Thank you! 👋🏻

**Comment by orestesgaolin** [comment]
I would propose bumping the version to 1.0.0 as the change is very much breaking for the users

**Comment by jeroen-meijer** [comment]
Good point, though aren't breaking changes to be expected _until_ 1.0.0? 👀

Also, I think @felangel mentioned there's an alternative package like this one that popped up recently that might make this package less relevant. Which one was that, and what are your thoughts on it @felangel? 🤔

**Comment by orestesgaolin** [comment]
If there's alternative, then I'd happily take a look at that. I'm working on the infinite pagination with bloc now, and it would be super useful
