### ISSUE TITLE
Support for two-way Pagination

### ISSUE THREAD

**Issue by xsahil03x** [VeryGoodOpenSource/very_good_infinite_list#18]
Currently `VeryGoodInfiniteList` is unable to be used for the chat message list as it only supports bottom pagination. A chat message list requires both top and bottom pagination in order to work perfectly.

It would be really great if `VeryGoodInfiniteList` supports two-way Pagination.

**Comment by felangel** [comment]
Hi @xsahil03x 👋 
Thanks for opening an issue!

Have you tried setting `reverse: true` on your list to achieve the desired effect? Let us know and thanks!

**Comment by xsahil03x** [comment]
Hey @felangel,

This will work if the list grows only in one direction. But a chat list requires the list to grow in both the top and bottom directions. This isn't possible as the listview will jump to the start if items are added in the opposite direction.

**Comment by renancaraujo** [comment]
@xsahil03x do you have any suggestion on how this could be implemented without changing the scope of the package and without any severe change in the API? If that is not possible, I am afraid this is "won't fix" case. The API on this package is heavily based on the concept the the "items count" and we don't want to break that.
