### ISSUE TITLE
scrollDirection parameter

### ISSUE THREAD

**Issue by ArunPrakashG** [VeryGoodOpenSource/very_good_infinite_list#20]
**Is your feature request related to a problem? Please describe.**
I had to configure scroll direction on one of my projects and while using this library i found it had no such parameter. this commit just adds that option to this library.

**Describe the solution you'd like**
Simply adds another parameter `scrollDirection` which is found in Flutter's `ListView` constructor to the library

**Comment by radikris** [comment]
@ArunPrakashG any update on this? I have the same issue, and would be very great if this amazing lib also has this scrollDirection option.

**Comment by ArunPrakashG** [comment]
@radikris this library doesn't seem to be maintained anymore.
I am currently using another package, which is maintained and offers all the features which I require.  
https://pub.dev/packages/infinite_scroll_pagination

You should give it a try and see if it adds to your use case.
