### ISSUE TITLE
Support Flutter Infinite Integration with Flutter Bloc

### ISSUE THREAD

**Issue by wisnuwiry** [VeryGoodOpenSource/very_good_infinite_list#23]
**Is your feature request related to a problem? Please describe.**

Often to fetch infinite data I use state management like bloc, and when I use ery_good_infinite_list I need Future to fetch data. And this will be completely different when using bloc.

**Describe the solution you'd like**

And this is an example of the implementation when using Bloc, maybe this can be a reference but for the implementation maybe you know better.

```dart
return BlocBuilder<SampleBloc, SampleState>(
      builder: (context, state) {
        return InfiniteList<String>(
          builder: InfiniteListBuilder<String>(
            success: (context, data) => Text('Success'),
            empty: (context) => Text('Empty'),
            error: (context, retry, error) => Text('Error'),
            loading: (context) => Text('Loading'),
          ),
          data: state is SampleSuccess ? state.data : '',
          isSuccess: state is SampleSuccess,
          isFailure: state is SampleFailure,
          isLoading: state is SampleLoading,
          itemLoader: () {
            // TODO: fetch data
          },
        );
      },
    );
```

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by felangel** [comment]
Hi @wisnuwiry 👋 
Thanks for opening an issue!

This appears to be using an outdated version of very_good_infinite_list. Can you let us know if this is still a problem on the latest version? You can refer to an example [here](https://github.com/VeryGoodOpenSource/very_good_infinite_list/blob/main/example/lib/advanced/advanced_example.dart). Closing for now 👍
