### ISSUE TITLE
CustomScrollView + InfiniteList

### ISSUE THREAD

**Issue by ezraaaa** [VeryGoodOpenSource/very_good_infinite_list#28]
**Is your feature request related to a problem? Please describe.**
When `InfiniteList` is used inside a `CustomScrollView`, it has 2 scroll views, resulting in a weird UX (refer to GIF)

**Describe the solution you'd like**
Have it working with CustomScrollView

**Describe alternatives you've considered**
- Tried using `NestedScrollView` but it has the same result as without one
- Tried using `NeverScrollablePhysics` but InfiniteList couldn't detect scroll changes and didn't load more items

**Additional context**

![Screen-Recording-2022-03-18-at-2 55 08-PM](https://user-images.githubusercontent.com/12880287/158954272-1e0b91b3-f933-48b0-95f6-86d47aa9d061.gif)

**Comment by alestiago** [comment]
Reproduced on `very_good_infinite_list: ^0.4.1`.

<details>

<summary> Flutter doctor </summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

<details>

<summary> Sample Code </summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:very_good_infinite_list/very_good_infinite_list.dart';

void main() {
  runApp(const MaterialApp(
    home: _Example(),
  ));
}

class _Example extends StatelessWidget {
  const _Example();

  @override
  Widget build(BuildContext context) {
    return Material(
      child: CustomScrollView(
        slivers: [
          CupertinoSliverRefreshControl(
            onRefresh: () => Future.delayed(const Duration(seconds: 1)),
          ),
          SliverFillRemaining(
            child: InfiniteList(
              itemCount: 30,
              onFetchData: () {},
              itemBuilder: (_, int index) => ListTile(
                title: Text('$index'),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

</details>

**Comment by alestiago** [comment]
@felangel what do we think about this issue? Do you think the addition of a `InfiniteSliverList` or `SliverInfiniteList` would be a nice addition?

**Comment by felangel** [comment]
> @felangel what do we think about this issue? Do you think the addition of a `InfiniteSliverList` or `SliverInfiniteList` would be a nice addition?

Yeah I think it could be nice to include an `InfiniteSliverList` variant (cc @renancaraujo @wolfenrain @erickzanardo).
