### ISSUE TITLE
SliverInfiniteList sometimes requires an extra pull to load more items

### ISSUE THREAD

**Issue by b-nugent** [VeryGoodOpenSource/very_good_infinite_list#41]
**Describe the bug**
My team had a SliverInfiniteList created by @alestiago (thanks Alejandro!!) before it was provided through this package in version 0.5.0. We attempted to swap in the SliverInfiniteList and noticed that by default the SliverInfiniteList sometimes requires an additional pull-up in order to load and display new items when the list reaches the end of what is loaded. We believe this may be due to how the effectiveItemCount is calculated, how the end of the list is determined, and how that results in the display of the loadingBuilder.

**To Reproduce**
Using a SliverInfiniteList that is the last sliver in a CustomScrollView, which has a loadingBuilder and the ability to load more list items:
- Quickly scroll through the list
     - The list reaches the end of displayable items and stops scrolling
- Pull up to attempt to keep scrolling
     - While pulling up, either the loading indicator displays or the list over-scrolls when using iOS BouncingScrollPhysics and shows no indicator
     - New list items are eventually loaded in and scrolling can continue

**Expected behavior**
What we expected (which reflects the behavior of the custom SliverInfiniteList made by VGV for our team) is that as the user scrolls down the list and reaches the end of the loaded data, the loading indicator (supplied by the loadingBuilder) is displayed at the very bottom of the list, and new list items begin to load. This causes the overall scrolling and loading to flow more naturally and reduces the need for the user to pull up again when the list runs out of displayable entries.

**Additional context**
Let us know if you'd like videos showcasing the difference in behavior, we're happy to send them to the team if needed.

**Comment by renancaraujo** [comment]
Hey @b-nugent, thanks for taking the time to report this. 

To add more context, this behavior is also observed in the nonsliver implementation before 0.5.0.  


LMK if you want to tackle it (based on that impl) otherwise we add this to the queue of stuff to do.

**Comment by alestiago** [comment]
@b-nugent thanks for the lovely comment and for opening the issue 🥹💙

@renancaraujo worked on the `SliverList` implementation. So I'm not sure straight away where this can be coming from. 

I was wondering if you have a minimal reproductive code you could share to have a look at 👀

**Comment by b-nugent** [comment]
Hey @renancaraujo and @alestiago! Here is the implementation that we're using:

```
class InfiniteSliverList extends StatefulWidget {
  const InfiniteSliverList({
    super.key,
    required this.onFetchData,
    required this.itemCount,
    required this.itemBuilder,
    required this.hasReachedMax,
    required this.isLoading,
  });
  
  final VoidCallback? onFetchData;
  final bool isLoading;
  final bool hasReachedMax;
  final int itemCount;
  final NullableIndexedWidgetBuilder itemBuilder;

  @override
  State<InfiniteSliverList> createState() =>
      _InfiniteSliverListState();
}

class _InfiniteSliverListState extends State<InfiniteSliverList> {
  @override
  Widget build(BuildContext context) {
    final childCount = widget.itemCount + (widget.hasReachedMax ? 0 : 1);

    return SliverList(
      delegate: SliverChildBuilderDelegate(
        childCount: childCount,
            (context, index) {
          final reachedEnd = index == childCount - 1;
          if (reachedEnd && !widget.hasReachedMax) {
            if (!widget.isLoading) {
              WidgetsBinding.instance.addPostFrameCallback((_) {
                widget.onFetchData?.call();
              });
              return const SizedBox.shrink();
            } else {
              return const Center(
                child: Padding(
                  padding: EdgeInsets.only(top: 16, bottom: 32),
                  child: CircularProgressIndicator(
                    color: Colors.grey,
                  ),
                ),
              );
            }
          }

          return widget.itemBuilder(context, index);
        },
      ),
    );
  }
}
```

This list brings up the loading indicator at the bottom of the list as the user is scrolling and more list items need to be loaded in. We swapped in the SliverInfiniteList with the same values for onFetchData, itemCount, itemBuilder, hasReachedMax, and isLoading, but found that the loading indicator doesn't show when the last of the list items is scrolled to. Instead, the user has to pull up a second time to see the loading indicator and bring up more items.

**Comment by renancaraujo** [comment]
After investigating, found that maxScrollExtent is not always up to date. We cannot rely on ScrollPosition anymore since it is not trustworthy for our case. The technique of refetching upon the last item build is quite clever since we can rely on  the sliver list dynamics to trigger refetch.

**Comment by renancaraujo** [comment]
Added a pr for this on #42
