### ISSUE TITLE
Option scrollExtentThreshold is not available

### ISSUE THREAD

**Issue by gabrielchaves7** [VeryGoodOpenSource/very_good_infinite_list#52]
**Describe the bug**
The package example shows a parameter called scrollExtentThreshold which is not available at version 0.7.0. Why it was removed??

**To Reproduce**

InfiniteList(scrollExtentThreshold: 100)

**Comment by mrocha98** [comment]
They removed scrollExtentThreshold in favor of cacheExtent on this PR: #42

**Comment by tomarra** [comment]
Looks like we do still have `scrollExtentThreshold` in the `README`. Let's either remove this or get it updated to the new property that should be used.
