### ISSUE TITLE
Add keyboardDismissBehavior property to InfiniteList

### ISSUE THREAD

**Issue by AristideVB** [VeryGoodOpenSource/very_good_infinite_list#53]
**Is your feature request related to a problem? Please describe.**
`ListView.builder` has a `keyboardDismissBehavior` property to hide keyboard onScroll

```
ListView.builder(
  keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
  itemCount: itemCount,
  itemBuilder: (BuildContext context, int index) {
    return ListTile(
      title: Text('Item ${index + 1}'),
    );
  },
)
```

**Describe the solution you'd like**
add a similar capability for [Very_good_infinite List](https://pub.dev/packages/very_good_infinite_list)

**Describe alternatives you've considered**
Using `NotificationListener<ScrollNotification>` is a good workaround
```
NotificationListener<ScrollNotification>(
      onNotification: (scrollNotification) {
        if (scrollNotification is ScrollStartNotification) {
          _hideKeyboard(context);
        }
        return false;
      },
      child: InfiniteList(
        itemBuilder: (context, item) => ListTile(title: Text('Item $item')),
      ),
    );
  }

  void _hideKeyboard(BuildContext context) {
    FocusScopeNode currentFocus = FocusScope.of(context);
    if (!currentFocus.hasPrimaryFocus) {
      currentFocus.unfocus();
    }
  }
```

**Comment by tomarra** [comment]
Currently no upvotes for this and no interaction from anyone. This is not work that we are prioritizing at this time. If you would like to see this feature please feel free to open a PR with the needed changes that can be reviewed and commented on.
