### ISSUE TITLE
not work with physics NeverScrollableScrollPhysics

### ISSUE THREAD

**Issue by erlangparasu** [VeryGoodOpenSource/very_good_infinite_list#54]
**Describe the bug**
not work with physics NeverScrollableScrollPhysics

**To Reproduce**
```
child: InfiniteList(
   physics: const NeverScrollableScrollPhysics(),
```

**Expected behavior**
work with physics NeverScrollableScrollPhysics

**Comment by renancaraujo** [comment]
Hello @erlangparasu, thanks for opening this issue.

I could not reproduce this. After adding `NeverScrollableScrollPhysics`  to our example app, the scrolling was deactivated as expected. 

Can you provide as reproducible sample (flutter app) for this?

**Comment by renancaraujo** [comment]
Hey @erlangparasu since this seems to be silent for a while, i am closing this for now. If anything comes up, dont hesitate on telling.
