### ISSUE TITLE
ci: Pub needs your authorization to upload packages on your behalf

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/very_good_infinite_list#74]
**Describe the bug**
After tagging the release hangs waiting for authorization.

**To Reproduce**
https://github.com/VeryGoodOpenSource/very_good_infinite_list/actions/runs/10580519772/job/29315586514

**Expected behavior**
Publishing succeeds.

**Comment by tomarra** [comment]
Possible that the Get ID Token step from here is what we need to add in, https://github.com/shorebirdtech/updater/blob/f37fee86a9fb1849d8a15da267a2de062d9e17d8/.github/actions/publish_flutter_package/action.yaml

**Comment by tomarra** [comment]
https://dart.dev/tools/pub/automated-publishing
