### ISSUE TITLE
fix: Not working properly with flutter Bloc

### ISSUE THREAD

**Issue by MuhammadAshouri** [VeryGoodOpenSource/very_good_infinite_list#77]
### Description

I'm using this List widget in a BlocBuilder and using cubit states
But seems it's not working correctly when state is changing.
Here is my code:
```
Widget build(BuildContext context) {
  return BlocBuilder<SearchCubit, SearchState>(
    builder: (context, state) {
      return InfiniteList(
        itemCount: state is SearchStateLoaded ? state.subtitles.length : 0,
        isLoading: state is SearchStateLoading,
        onFetchData: _fetchData,
        separatorBuilder: (context, index) => const SizedBox(height: 16),
        itemBuilder: (listContext, index) {
          return Placeholder();
        },
      );
    },
  );
}
```

### Steps To Reproduce

I also checked if state is changing by printing the state and it's doing its job.

### Expected Behavior

when _fetchData called state gets updated but loading and items count not updating

**Comment by alestiago** [comment]
@MuhammadAshouri thanks for opening an issue!

Can you provide a complete minimal reproductive sample that we can execute? Maybe as a standalone [gist](https://gist.github.com/)?

We've seen Bloc being used with InfiniteList in the past without any issues, so we need a complete minimal reproductive to assess the issue.

**Comment by MuhammadAshouri** [comment]
It's a simple cubit. But I wrote a gist with exact functionality of my project
https://gist.github.com/MuhammadAshouri/04bb5de5becc66ee3fcbf114ddf2971e

**Comment by wolfenrain** [comment]
Your gist does not provide the `SearchState` class. But I suspect your state class does not have the correct equality operation implement and therefore bloc might not detect your state change the way you want it too. It would be amazing if you could provide a simple Flutter project with your reproduce-able problem, that way we can make sure it isn't this package.

But as @alestiago already mentioned we have used it with bloc before so I suspect it is your state class.

**Comment by tomarra** [comment]
Hi @MuhammadAshouri, given that this is not an issue with the package and looks to be more of an implementation problem I'm going to close this issue as a "Won't Fix".

There is an [infinite list example in the bloc documentation](https://bloclibrary.dev/tutorials/flutter-infinite-list/) which may be a good place to start to solve your issue. It doesn't directly use this package but the concept is still the same.
